# Generated by Django 4.1.1 on 2022-09-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="medias"),
        ),
    ]
