# Generated by Django 4.1.1 on 2022-09-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_medias", "0002_alter_postmedia_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="mimetype",
            field=models.CharField(max_length=10),
        ),
    ]
