# Generated by Django 4.1.1 on 2022-09-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_medias", "0003_alter_postmedia_mimetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="media",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
