# Generated by Django 4.1.1 on 2022-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_medias", "0004_alter_postmedia_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="media",
            field=models.FileField(null=True, upload_to="post_medias"),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="thumbnail",
            field=models.ImageField(upload_to="thumbnails"),
        ),
    ]
